name: riverpod_sample
description: Sample SM riverpod
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3

  freezed: ^1.1.1
  freezed_annotation: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:

  uses-material-design: true